# Generated by Django 2.0.7 on 2018-08-28 06:50

from django.db import migrations, models
import uuid

from products.models import Product


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_price'),
    ]

    def gen_uuid(apps, schema_editor):
        for row in Product.objects.all():
            row.slug = uuid.uuid4()
            row.save()

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.uuid1, unique=True),
        ),
        migrations.RunPython(gen_uuid),

        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, unique=True),
        ),
    ]
